version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: vending-machine
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  dbdata6:
